name: Pull Request Check

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  validate_title:
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@e9fabac35e210fea40ca5b14c0da95a099eff26f # v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
